name: 'LGTM Reaction hayuna'
description: 'Send LGTM reaction as image or GIF '
author: 'micnncim'
inputs:
  trigger:
    description: 'Trigger comment on issue to send reaction'
    required: false
    default: '["^lgtm$", "^[gG]ood [jJ]ob!?$"]'
  overide:
    description: 'Whether the original comment is overridden'
    required: false
    default: false
  source:
    description: 'Source providing LGTM image'
    required: false
    default: lgtmapp
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: 'thumbs-up'
  color: 'blue'
