name: 'Telegram Action 98797979879879'
description: 'Telegram notification for workflow set up with Github Actions'
author: <name>
inputs:
  botToken:
    description: 'The Telegram Bot token'
    required: true
  chatId:
    description: 'The target to which the message will be sent, can be a Telegram Channelor Group'
    required: true
  jobStatus:
    description: 'The current sttaus of the job: job.status, defaults to `success`'
    default: 'success'
  skipSuccess:
    description: 'Only non-success notification will be sent if true, include success notification otherwise, defaults to `true`'
    default: 'true'
runs:
  using: 'node12'
  main: 'lib/main.js'
